about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [    
    path('about/', views.about, name='about'),
    # path('profile', views.profile, name='profile'),
]

fortune_board/urls.py
from django.urls import path
from . import views

app_name = "fortune_board"

urlpatterns = [    
    
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('', views.PostList.as_view(), name="post_list"),
    path('<int:pk>/', views.PostDetail.as_view(),),    
    path('<int:pk>/new_comment/', views.new_comment),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    # path('', views.index, name='fortune_board'),
    # path('<int:pk>/', views.single_post_page),
    # path('profile', views.profile, name='profile'),
]

fortune_board/models.py
from django.db import models
from django.conf import settings
# from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name      

    def get_absolute_url(self):
        return f'/fortune_board/tag/{self.slug}/'   

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name      

    def get_absolute_url(self):
        return f'/fortune_board/category/{self.slug}/'
    

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):

    title = models.CharField(max_length=200)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL, null=True)
    content = MarkdownxField()
    publish_confirm = models.BooleanField(default=True)
    
    post_image = models.ImageField(upload_to='fortune_board/images/%Y/%m/%d/', blank=True, null=True)    

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/fortune_board/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)
        

class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    content = models.TextField()
    publish_confirm = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.image.url:
            return self.author.image.url

        

fortune_board/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

fortune_board/views.py
from django.views.generic import ListView,DetailView, CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404

from .models import Post, Category, Tag, Comment
from .forms import CommentForm

from django.utils.text import slugify
from django.db.models import Q

# Create your views here.
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    
    post = comment.post 

    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
             return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


def tag_page(request, slug):
    
    tag = Tag.objects.get(slug=slug)
    post_list = Tag.objects.all()

    return render(
        request,
        'fortune_board/post_list.html',
        {
            'post_list':post_list,
            'categories':Category.objects.all(),
            'no_category_post_count':Post.objects.filter(category=None).count(),
            'tag':tag,
        }
    )

def category_page(request, slug):
    if slug == "no_category":
        category = "미분류"
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'fortune_board/post_list.html',
        {
            'post_list':post_list,
            'categories':Category.objects.all(),
            'no_category_post_count':Post.objects.filter(category=None).count(),
            'category':category,
        }
    )

class PostList(ListView):
    model = Post    
    # ordering = '-pk'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(publish_confirm=True).order_by('-pk')    

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context

    # context_object_name = ''
    # template_name='fortune_board/index.html'

class PostDetail(DetailView):
    model = Post
    # template_name = "fortune_board/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm

        return context


class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = [
        'title', 'content', 'post_image', 'category','publish_confirm', 
    ]

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tagging, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tagging.slug = slugify(t, allow_unicode=True)
                        tagging.save()
                    self.object.tag.add(tagging)

            return response
        else:
            return redirect('fortune_board/')

class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    fields = [
        'title', 'content', 'post_image', 'category','publish_confirm', 
    ]

    template_name = "fortune_board/post_update_form.html"

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tag.exists():
            tags_str_list = list()
            for t in self.object.tag.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request,  *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tag.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()

            tags_str = tags_str.replace(',',';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tagging, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tagging.slug = slugify(t, allow_unicode=True)
                    tagging.save()
                self.object.tag.add(tagging)

        return response

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):        
        q = self.kwargs['q']
        
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tag__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context






# def index(request):

#     post_list= Post.objects.filter(publish_confirm=True).order_by('-pk')

#     return render(
#         request, 
#         'fortune_board/index.html',
#         { 'posts': post_list, }
#         )


# def single_post_page(request, pk):
#     post = Post.objects.filter(publish_confirm=True).get(pk=pk)

#     return render(
#         request,
#         'fortune_board/single_post_page.html',
#         { 'post': post }
#         )

fortune_board/templates/fortune_board/comment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-8 mx-auto">
    <br/>
    <br/>
    <h1>댓글 수정</h1>
    <hr/>    
    <form method="post" id="comment-form">
        {% csrf_token%}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
</div>
{% endblock %}

fortune_board/templates/fortune_board/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div id ="post-area">
    <div class="col-md-8 mx-auto text-left">
        
        <h2 align="center">{{  post.title }}</h2>

        {% if post.category %}
            <span class="badge badge-link float-end">category: {{post.category}}</span>
        {% else %}
            <span class="badge badge-link float-end">category: 미분류</span>
        {% endif %}

        <hr/>     
        <div align="right">
            {% if user.is_authenticated and user == post.author %}
                <a class="btn btn-info btn-sm float-end" href="/fortune_board/update_post/{{post.pk}}/" role="button"><i class="fas fa-pen"></i>포스트 수정하기</a>
            {% endif %}
        </div>
        <h5>
            <div align="left">   -글쓴이: <a href="#">{{post.author}}</a>( {{ post.created_at|date:"Y-m-d" }})</div>
        </h5>   
        <br>
        <div class="card mb-4">
            {% if post.post_image %}
                <img class="figure-img img-fluid rounded mx-auto" src="{{ post.post_image.url }}"   width="400" alt="{{post.title}} post_image">
            {% endif %}

        </div>
        <p> {{  post.get_content_markdown | safe }} </p>    

        {% if post.tag %}
            <i class="fas fa-tag"></i>
            {% for t in post.tag.iterator %}
                <a href="{{ t.get_absolute_url }}"><span class="badge badge-link">tag: {{ t }}</span></a>
            {% endfor %}
            <br/>
            <br/>
        {% endif %}
        
    </div>
    <br> 
</div>
<div id ="comment-area">
    <div class="col-md-8 mx-auto text-left">
        <p>댓글 달기</p>
        {% if user.is_authenticated %}
        
        <form class="mb-4" id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
            {% csrf_token %}
            <div class="form-group">
               {{ comment_form | crispy }}
            </div>
            <div align="right">
                <button type="submit" class="btn btn-primary">Summit</button>
            </div>
            
        </form>
        {% else %}
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">
                Log in and Leave a comment
            </a>
        {% endif %}
    </div>
    
    {% if post.comment_set.exists %}
        {% for comment in post.comment_set.iterator %}
            <div class="col-md-8 mx-auto text-left" id="comment-{{ comment.pk }}">
                <img class="d-flex mr-r rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="60px">

                {% if user.is_authenticated and comment.author == user %}

                    <div class="float-right">
                        <a role="button" class="btn btn-sm btn-info" id="comment-{{comment.pk}}-update-btn" 
                        href="/fortune_board/update_comment/{{comment.pk}}">
                            수정
                        </a>

                        <a role="button" class="btn btn-sm btn-danger" id="comment-{{comment.pk}}-delete-modal-btn" 
                        href="#" data-toggle="modal" data-target="#deleteCommentModal-{{comment.pk}}">삭제</a>
                    </div>
                    

                    <!-- Modal -->
                    <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" 
                    role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
                                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <del>{{ comment | linebreaks }}</del>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <a role="button" class="btn btn-danger" href="/fortune_board/delete_comment/{{comment.pk}}/">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif  %}

                <div class="media-body">
                    <h5 class="mt-0">
                        {{comment.author.username}} &nbsp;&nbsp;<small class="text-muted">{{comment.created_at | date:"Y-m-d h:i:s"}}</small>
                    </h5>
                    <p>{{ comment.content | linebreaks }}</p>
                    {% if comment.created_at != comment.updated_at %}
                        <p class="text-muted float-right">
                            <small>Updated: {{comment.updated_at | date:"Y-m-d h:i:s"}}</small>
                        </p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock content %}}>

fortune_board/templates/fortune_board/post_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<h1 align="center">Create New Post</h1>
<hr/>
<div id ="post-area">
    <div class="col-md-8 mx-auto">
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {{ form | crispy}}
            <div id="div_id_tags_str">
                <label>Tags:</label>
                <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control">
            </div>
            <br/>
            {% comment %} <table>
                <tr>
                    <th><label for="id_tags_str" >Tags:</label></th>
                    <td><input type="text" name="tags_str" id="id_tags_str"></td>
                </tr>
            
            </table>             {% endcomment %}
            <button type="submit" class="btn btn-primary float-end">Submit</button>
        </form>

        {{ form.media }}
    </div>
</div>

        
{% endblock %}

fortune_board/templates/fortune_board/post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="d-flex flex-row justify-content-center">
    <div>
        <h1>
            궁물쌤의 운세 게시판 &nbsp&nbsp&nbsp&nbsp
            {% if search_info %}<small class="text-muted">{{ search_info }}</small>{% endif %}
            {% if category %}<span class="badge badge-secondary">{{category}}</span>{% endif %}
        </h1>   
    </div>    
    &nbsp;&nbsp;&nbsp;&nbsp;
    <div>        
        {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff %}
            
                <a class="btn btn-warning" href="/fortune_board/create_post/" role="button">
                    <i class="fas fa-pen"></i>
                    &nbsp 새로운 글 작성
                </a>
            {% endif %}
        {% endif %}
    </div>    
</div>
<hr/>
<div class="col-md-12 mx-auto">    
    <div class="row">            
        <div id="main_area" class="col-md-8 mx-auto">  
            {% if post_list.exists %}
                {% for p in post_list %}       
                    <div>
                        <h2>
                            <div align="center"><a href='{{ p.get_absolute_url }}'>
                                {{  p.title }}</a>                        
                                &nbsp&nbsp&nbsp&nbsp
                                {% if p.category %}     
                                    <span class="badge badge-primary">{{ p.category }}</span>   
                                {% else %}
                                    <span class="badge badge-primary">미분류</span> 
                                {% endif %}                                 
                            </div>
                        </h2>
                            <div align="right" class="card-footer">
                                by <a href="#">{{p.author}}</a>
                            </div>
                            <div align="right" class="card-footer">
                                Post on {{p.created_at|date:"Y-m-d"}}</a>
                            </div> 
                    </div>                            
                    <div class="card mb-4">   
                        {% if p.post_image %}         
                            <img class="figure-img img-fluid rounded mx-auto" src="{{ p.post_image.url }}"  alt="{{ p }} post image" >   
                        {% endif %}         
                    </div>
                    <p class ="card-text"> {{  p.get_content_markdown | truncatewords_html:50 | safe }} </p>

                    {% if p.tag %}
                    <i class="fas fa-tag"></i>
                        
                        {% for t in p.tag.iterator %}
                            <a href="{{ t.get_absolute_url }}"><span class="badge badge-light">태그 : {{ t }}</span></a>
                        {% endfor %}
                        <br/>
                        <br/>
                    {% endif %}     
                    <br/>
                    <br/>

                {% endfor %}
            {% else %}
                    <div>
                        <h3 align="center">아직 게시물이 없습니다.</h3>
                    </div>
                        
            {% endif %}
            <br>
        </div>
        <div class="col-md-3 mx-auto" id="category-card">
            {% comment %} <h5 class="card-header">카테고리</h5> {% endcomment %}
            <h5 align="left">Category</h5>
            <div class="card-body">
                <div class="row">
                    <ul align="left">
                        {% for category in categories %}
                            <li>
                                <a href="{{ category.get_absolute_url }}"> {{category}} ({{ category.post_set.count }}) </a>  
                            </li>                   
                        {% endfor %}
                            <li><a href="/fortune_board/category/no_category/"> 미분류 ({{ no_category_post_count }})</a>
                    </ul>
                </div>
            </div>

            <!--Search Widget-->
            <div class="Card my-4" id="category-search">
                <h5 class="card-header">Search(제목,태그)</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for..." id="search-input">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button" onclick="searchPost();">Go!</button>
                        </span>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function searchPost() {
        let searchValue = document.getElementById('search-input').value.trim();
        if (searchValue.length > 1) {
            location.href = "/fortune_board/search/" + searchValue + "/";
        } else {
            alert('검색어(' + searchValue + ')가 너무 짧습니다.');
        }
    };

    document.getElementById('search-input').addEventListener('keyup',function(event)
    {
        if(event.key == 'Enter'){
            searchPost();
        }
    });
</script>


{% if is_paginated %}
    <!--Pagination-->
    <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr;Older</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&larr;Older</a>
            </li>
        {% endif %}

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer&rarr;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer&rarr;</a>
            </li>
        {% endif %}

    </ul>    
{% endif %}


{% endblock content %}>

fortune_board/templates/fortune_board/post_update_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div id ="post-area">
    <div class="col-md-8 mx-auto">
        <h1>Post 수정하기</h1>
        <hr/>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy}}
            <div id="div_id_tags_str">
                <label>Tags:</label>
                <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control" value="{{ tags_str_default }}">
            </div>
            <br/>
            {% comment %} <table>
                {{ form }}
                <tr>
                    <th><label for="id_tags_str" >Tags:</label></th>
                    <td><input type="text" name="tags_str" id="id_tags_str" value="{{ tags_str_default }}"></td>
                </tr>
            </table> {% endcomment %}
            <div align="center">
                <button type="submit" class="btn btn-primary float-right">Submit</button>
            </div>
        </form>
    </div>
</div>
    
        
{% endblock %}

fortune_board/templates/fortune_board/single_post_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-md-8 mx-auto text-left">
    <h3>{{  post.title }}</h3>
    <hr/>
        
    <h4> {{post.created_at}}   -글쓴이: {{post.author}}</h3>        
    <p> {{  post.content }} </p>
    
</div>
<br> 


{% endblock content %}}>