about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [    
    path('about/', views.about, name='about'),
    # path('profile', views.profile, name='profile'),
]

yughyo/urls.py
from django.urls import path
from . import views

app_name = "yughyo"

urlpatterns = [
    path('<int:pk>/', views.iching),
    path('', views.front, name='yughyo_front'),
    path('new/', views.question, name='question_new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('result/<int:pk>/', views.result, name='result'),
]

yughyo/models.py
from django.db import models
from accounts.models import MyUser
from django.conf import settings

# Create your models here.
class Iching(models.Model):
    g_id = models.IntegerField(primary_key=True)
    g_name = models.CharField(max_length=30)
    g_content = models.CharField(max_length=500)
    h_content_1 = models.CharField(max_length=500)
    h_content_2 = models.CharField(max_length=500)
    h_content_3 = models.CharField(max_length=500)
    h_content_4 = models.CharField(max_length=500)
    h_content_5 = models.CharField(max_length=500)
    h_content_6 = models.CharField(max_length=500)
    hope = models.CharField(max_length=500)
    consult = models.CharField(max_length=500)
    business = models.CharField(max_length=500)
    trade = models.CharField(max_length=500)
    contract = models.CharField(max_length=500)
    law = models.CharField(max_length=500)
    job = models.CharField(max_length=500)
    promotion = models.CharField(max_length=500)
    school = models.CharField(max_length=500)
    move = models.CharField(max_length=500)
    travel = models.CharField(max_length=500)
    love = models.CharField(max_length=500)
    marry = models.CharField(max_length=500)

    class Meta:
        ordering = ['g_name']


class Question(models.Model):
    CATEGORY_CHOICES = (
        ('hope', '소원'), ('consult', '상담'), ('business', '사업'), ('trade', '매매'),
        ('contract', '계약'), ('law', '소송'), ('job', '취업'), ('promotion', '승진/진급'),
        ('school', '입학'), ('move', '이사'), ('travel', '여행'), ('love', '연애/사랑'), ('marry', '결혼')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    question_text = models.CharField(max_length=200)
    jum = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

#
# class Choice(models.Model):
#     question = models.OneToOneField(Question, on_delete=models.CASCADE)
#     result_number = models.IntegerField()
#     created_at = models.DateTimeField(auto_now_add=True)
#
# class Result(models.Model):
#     result_name = models.OneToOneField(Iching, on_delete=models.CASCADE)

yughyo/forms.py
from django import forms
from .models import Question

from django.forms import Textarea

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['category', 'question_text', ]
        widgets = {
            'question_text': Textarea(attrs={
                'class': "form-control",
                'style': 'max-width: 1200px;',
                'placeholder': '궁금한 것을 입력하세요.'
            })
        }

yughyo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import MyUser
from .forms import QuestionForm
from .models import Iching, Question
from accounts.models import MyUser

from django.utils import timezone
import random

# Create your views here.
def iching(request,pk):
    data_list = Iching.objects.get(g_id=pk)
    g_id = data_list.g_id
    g_name = data_list.g_name
    g_content = data_list.g_content
    h_content_1 = data_list.h_content_1
    h_content_2 = data_list.h_content_2
    h_content_3 = data_list.h_content_3
    h_content_4 = data_list.h_content_4
    h_content_5 = data_list.h_content_5
    h_content_6 = data_list.h_content_6
    hope = data_list.hope
    consult = data_list.consult
    business = data_list.business
    trade = data_list.trade
    contract = data_list.contract
    law = data_list.job
    job = data_list.job
    promotion = data_list.promotion
    school = data_list.school
    move = data_list.move
    travel = data_list.travel
    love = data_list.love
    marry = data_list.marry

    context = {
        'g_id': g_id,
        'g_name': g_name,
        'g_content': g_content,
        'h_content_1': h_content_1,
        'h_content_2': h_content_2,
        'h_content_3': h_content_3,
        'h_content_4': h_content_4,
        'h_content_5': h_content_5,
        'h_content_6': h_content_6,
        'hope': hope,
        'consult': consult,
        'business': business,
        'trade': trade,
        'contract': contract,
        'law': law,
        'job': job,
        'promotion': promotion,
        'school': school,
        'move': move,
        'travel': travel,
        'love': love,
        'marry': marry
    }

    return render(request, "yughyo/list.html", context)


@login_required(login_url="../accounts/login")
def front(request):
    list = Question.objects.filter(user=request.user)
    context = {
        'list': list,
    }
    return render(request, 'yughyo/front.html', context)

@login_required
def question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.created_at = timezone.now()
            question.jum = random.randint(1, 64)
            question.user = request.user
            question.save()
            return redirect('yughyo:detail', pk=question.id)
    else:
        form = QuestionForm()
        context = {'form': form}
    return render(request, 'yughyo/input.html', context)


@login_required
def detail(request, pk):
    question = Question.objects.get(pk=pk)
    cat = question.category
    jum_id = question.jum
    question_text = question.question_text
    iching = Iching.objects.get(pk=jum_id)
    user = question.user

    if cat == "hope":
        jum = iching.hope
    elif cat == "consult":
        jum = iching.consult
    elif cat == "business":
        jum = iching.business
    elif cat == "trade":
        jum = iching.trade
    elif cat == "contract":
        jum = iching.contract
    elif cat == "law":
        jum = iching.law
    elif cat == "job":
        jum = iching.job
    elif cat == "promotion":
        jum = iching.promotion
    elif cat == "school":
        jum = iching.school
    elif cat == "move":
        jum = iching.move
    elif cat == "travel":
        jum = iching.travel
    elif cat == "love":
        jum = iching.love
    elif cat == 'marry':
        jum = iching.marry
    else:
        print(f"더 이상 데이터가 없습니다.")

    g_name = iching.g_name
    g_content = iching.g_content

    myBirthDay = user.birth_day
    myBirthTime = user.birth_time
    createdTime = question.created_at

    context = {
        'question': question_text,
        'category': cat,
        'jum': jum,
        'name': g_name,
        'content': g_content,
        'user': user,
        'birth_day': myBirthDay,
        'birth_time':myBirthTime,
        'createdTime': createdTime
    }
    if request.user != question.user:
        return redirect("{% url 'today_api:today' %}")
    else:
        return render(request, 'yughyo/detail.html', context)

def result(request, pk):
    result = Iching.objects.get(pk=pk)

yughyo/templates/yughyo/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
    <div class="col-md-8 mx-auto text-center">
        <h2>궁금한 것에 대한 답변입니다.</h2>
        <div class="danger">
            (재차 삼차 물어보는 것은 점에 대한 불신입니다.
        점의 효력이 떨어지는 것이니 조심하시기 바랍니다.)
        </div>
    </div>

    <div class="col-md-8 mx-auto text-left">
        <hr>

    </div>
    <div  class="col-md-8 mx-auto text-left"><br>

        <div class="col-md-8 mx-auto text-center">
            <div class="result">
                <h2>{{name}} 괘</h2>
            </div>
        </div>
        <hr>
         괘에 대한 설명 : <br>
            {{ content }}
        <br>
        <hr>
        <div>
                질문 내용:
            <h4>
            <br> {{ question }}
            </h4>
        </div>
        <div class="category">
            질문 분야:
            {% if category == 'hope' %}
            소원
            {% elif category == 'consult' %}
            상담
            {% elif category == 'business' %}
            사업
            {% elif category == 'trade' %}
            매매
            {% elif category == 'contract' %}
            계약
            {% elif category == 'law' %}
            소송
            {% elif category == 'job' %}
            취업
            {% elif category == 'promotion' %}
            승진/진급
            {% elif category == 'school' %}
            입학
            {% elif category == 'move' %}
            이사
            {% elif category == 'travel' %}
            여행
            {% elif category == 'love' %}
            연애/사랑
            {% elif category == 'marry' %}
            결혼
            {% endif %}
        </div>
        <br>질문자:{{ user }}님
        <br>내어난 날: {{birth_day}}
        <br>태어난 시: {{birth_time}}
        <br>점을 친 시간: {{createdTime}}
        <hr>
        <br>
        <div class="predict">
            질문에 대한 예언:
            <br>
            {{ jum }}
        </div>
        <br>
        <hr>
        <br>
        <div>
            위 예언을 가벼운 마음으로 여기시고 너무 맹신하지는 마시기 바랍니다.<br>
            이 콘텐츠를 즐기는 마음으로 생각하세요.<br>
            매일 행복하시길....바라며...
        </div>

    </div>
</div>

{% endblock %}

yughyo/templates/yughyo/front.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div  class="col-md-8 mx-auto">
    <div class="col-md-8 mx-auto text-center">
        <h1>미래가 궁금하시면 물어보세요</h1>
        <br>
        <button type="button" class="btn btn-info"><a href="{% url 'yughyo:question_new' %}">질문하기</a></button>
    </div>
<<<<<<< HEAD
    <div  class="col-md-8 mx-auto text-center">
        예전에 물어 보았던 것들..
    </div>
    <div  class="col-md-8 mx-auto text-left">   
                      
            <div>
                {% for i in list %}   
                    <div>
                        <span align="left">
                            <a class="col-md-8 mx-auto text-left">{{ i }}</a>
                        </span>  
                        <span align="right">
                            {{i.created_at}}
                        </span>                      
                    </div> 
                {% endfor %}
=======
    <div>
        <table>
            <div class="container-fluid" >
                <div class="row">
                    <tr ailgn="right>
                        <th colspan="2">지난 질문들~~</th>
                    </tr>
                    <hr>
                    <td></td>
                    <td>질문</td>
                    <td></td>
                    <td align="center">날짜</td>
                    {% for i in list %}
                        <tbody>
                            <tr>
                                <td>[{{ i.get_category_display }}] </td>
                                <td> {{ i }} </td>
                                <td> -- </td>
                                <td ailgn="right"> {{i.created_at}}</td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </div>
>>>>>>> 197762b40b4dfd7075c39ba66922ac42fd5cb65a
            </div>
    </div>
</div>
{% endblock %}

yughyo/templates/yughyo/input.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-8 mx-auto text-center">
    <h1>궁금한 것을 물어보세요. 선생님(쌤)에게 </h1>
    <h2>궁물쌤이 알려줍니다</h2>
    질문을 입력 하세요.<br> 되도록이면 자세히 입력하시기 바랍니다.<br> 
    질문의 결과가 (예/아니오) 나오도록 질문을 하시면 더 이해하기 좋습니다.<br> 
    200자 이내로 입력하세요. 
    <br>
    <div  class="col-md-8 mx-auto text-left">
        <p>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <button type="submit" class="btn btn-primary">알고싶어요</button>
            </form>
        </p>
    </div>
</div>


{% endblock content %}}>

yughyo/templates/yughyo/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="title">
    <h1>{{ g_id }}&nbsp;{{g_name}}</h1>
</div>
<div class="big_content">
    <h2>{{g_content}}</h2>
</div>
<div class="hyo_1">
    1효: {{h_content_1}}
</div>
<div class="hyo_2">
    2효: {{h_content_2}}
</div>
<div class="hyo_3">
    3효: {{h_content_3}}
</div>
<div class="hyo_4">
    4효: {{h_content_4}}
</div>
<div class="hyo_5">
    5효: {{h_content_5}}
</div>
<div class="hyo_6">
    6효: {{h_content_6}}
</div>

</body>
</html>

yughyo/templates/yughyo/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>결과 페이지</h1>
</body>
</html>