about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [    
    path('about/', views.about, name='about'),
    # path('profile', views.profile, name='profile'),
]

accounts/urls.py
from django.conf import settings
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<int:pk>/', views.profile, name='profile'),   
]

my_today/urls.py
from django.urls import path
from . import views

app_name = "my_today"

urlpatterns = [
    path('', views.mytoday, name='mytoday'),
]

today_api/urls.py
from django.urls import path
from . import views

app_name = "today_api"

urlpatterns = [
    path('',  views.today_catch,),
    path('about/', views.about, name='about'),
    path('<int:pk>/', views.today12),
    path('today/', views.today_catch, name='today'),
]

yughyo/urls.py
from django.urls import path
from . import views

app_name = "yughyo"

urlpatterns = [
    path('<int:pk>/', views.iching),
    path('', views.front, name='yughyo_front'),
    path('new/', views.question, name='question_new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('result/<int:pk>/', views.result, name='result'),
]

about/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from accounts.models import MyUser

# Create your views here.

@login_required
def about(request, pk):
    if request.method == 'POST':
        pass
    # user = get_user_model().objects.get(pk=pk)

    # year = user.birth_day.strftime("%Y")
    # month = user.birth_day.strftime("%m")
    # day = user.birth_day.strftime("%d")
    # #
    # calendar = KoreanLunarCalendar()
    # calendar.setSolarDate(int(year), int(month), int(day))
    # lunar = calendar.LunarIsoFormat()
    # gabja = calendar.getGapJaString()
    # hanja = calendar.getChineseGapJaString()

    # context = {
    #     "lunar": lunar,
    #     "gabja": gabja,
    #     "hanja": hanja,
    # }

    return render(request, 'accounts/profile.html',)

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-8 mx-auto text-center">
    <h1>궁물쌤에 대하여</h1>
    <div>
        궁물쌤은 "궁금한 것을 물어보세요.쌤에게.."의 약자로써, 운세와 관련된 콘텐츠를 제공합니다.<br>
        모바일 앱으로 용한점집, 용한타로, 용한띠별운세, 용한손금, 용한꿈풀이 등을 개발하였고,<br>
        더 좋은 콘텐츠를 만들기 위해 노력하고 있습니다.<br>
        제휴나 협력, 조언 등의 의견은 gungmul@kakao.com 으로 보내주시기 바랍니다.<br>
        사주나 IT창업과 관련된 상담도 합니다...그것도 이메일로 신청하시기 바랍니다.<br>
    </div>
</div>
<br>
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>궁물쌤</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" crossorigin="anonymous">
    
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    
    <script src="https://kit.fontawesome.com/2dda1c66a8.js" crossorigin="anonymous"></script>
    <style>
<!--      table, th, td {-->
<!--        border: 1px solid #bcbcbc;-->
<!--      }-->
      .danger {
       color: red;
       }
       .result {
       color: blue;
       }
       .predict {
       color: green;
       }
       .today-content {
       color: grey;
       }
    </style>
</head>
<body>

{% include "header.html" %}
<div>
    {% block content %}
    {% endblock content %}
</div>

</body>
{% include "footer.html" %}
</html>

templates/footer.html
<div class="b-example-divider"></div>

<div class="container">
  <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
      <p class="text-muted">&copy;신비 2023</p>
    </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Reference</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="http://iching.kr" class="nav-link p-0 text-muted">대동학회</a></li>

      </ul>
    </div>

    <div class="col mb-3">
      <h5>Contact</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">이메일: gungmul@kakao.com</a></li>

      </ul>
    </div>

    <div class="col mb-3">
      <h5>Advertisement</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="{% url 'single_pages:flower' %}" class="nav-link p-0 text-muted">꽃배달</a></li>

      </ul>
    </div>
  </footer>
</div>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'single_pages:landing' %}"><img src="{% static 'size_64_2.png' %}">&nbsp&nbsp궁물쌤</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'single_pages:landing' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'fortune_board:post_list' %}">게시판</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          운세
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'today_api:today' %}">오늘의 띠별운세</a>
          <a class="dropdown-item" href="{% url 'my_today:mytoday' %}">나만의 오늘의 운세</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'yughyo:yughyo_front' %}">주역점</a>
        </div>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li> {% endcomment %}
      
    </ul>      

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div align="">
          {% if not user.is_authenticated %}
            <button type="button" class="btn btn-link"><a href="{% url 'accounts:login' %}">로그인</a></button>           
          {% else %}
            <button type="button" class="btn btn-link"><a href="{% url 'accounts:logout' %}">로그아웃</a></button>
            {% comment %} <button type="button" class="btn btn-link"><a href="{% url 'accounts:profile' %}">프로필</a></button> {% endcomment %}
        </div>
      </li>
      &nbsp&nbsp
      <li class="nav-item">
        {% endif %}
        <button type="button" class="btn btn-light"><a href="{% url 'accounts:signup' %}">회원가입</a></button>
      </li>
    </ul>
  </div>
</nav>

  {% comment %} <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <div class="navbar-brand">        
        <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'fortune_board:post_list' %}"><img src="{% static 'size_64_2.png' %}"> 궁물쌤</a></h5>        
    </div>    

    <ul class="navbar-nav">      
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'today_api:today' %}" data-toggle="dropdown" aria-expanded="false">운세</a>
       
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'today_api:today' %}">오늘의 띠별 운세</a>
          <a class="dropdown-item" href="{% url 'my_today:mytoday' %}">나만의 오늘의 운세</a>
          <a class="dropdown-item" href="{% url 'yughyo:yughyo_front' %}">주역점</a>          
        </div>
      </li>
      <li>    
      <a  class="p-2 text-dark" href="{% url 'fortune_board:post_list' %}">게시판</a>
      
      <a class="p-2 text-dark" href="#">Features</a>   
    </ul>
  </div> {% endcomment %}


{% comment %}     
    <div class="col-md-3 text-end">
      {% if not user.is_authenticated %}
        <button type="button" class="btn btn-outline-primary me-2"><a href="{% url 'accounts:login' %}">로그인</a></button>
      {% else %}
        <button type="button" class="btn btn-outline-primary me-2"><a href="{% url 'accounts:logout' %}">로그아웃</a></button>
      {% endif %}
      <button type="button" class="btn btn-info"><a href="{% url 'accounts:signup' %}">회원가입</a></button>
    </div>
  </div>

 {% endcomment %}